spring:
  application:
    name: mcp-pilot

  thread:
    virtual:
      enabled: true

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-pro
            thinkingBudget: 1000
        embedding:
          api-key: ${GEMINI_API_KEY}
          text:
            options:
              model: text-embedding-004
    mcp:
      server:
        type: SYNC
        annotation-scanner:
          enabled: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

management:
  server:
    port: 8081 # 관리용 포트를 8081로 완전히 분리로 8080 포트를 통해 시스템 내부 정보(환경변수, 메트릭 등) 유출되는 것을 차단
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true # Liveness/Readiness 전용 경로 활성화