spring:
  application:
    name: mcp-pilot

  thread:
    virtual:
      enabled: true

  ai:
    retry:
      max-attempts: 1
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-3.1-flash-lite
            thinkingBudget: 1000
        embedding:
          api-key: ${GEMINI_API_KEY}
          text:
            options:
              model: gemini-embedding-001
    mcp:
      server:
        type: SYNC
        annotation-scanner:
          enabled: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true

notion:
  api:
    token: ${NOTION_TOKEN}
    database-id: ${NOTION_DATABASE_ID}
    version: 2026-03-11

management:
  server:
    port: 8081 # 관리용 포트를 8081 분리로 8080 포트를 통해 시스템 내부 정보(환경변수, 메트릭 등) 유출되는 것을 차단
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true # Liveness/Readiness 전용 경로 활성화

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.springframework.ai: DEBUG