plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.0'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.mcp'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
}

ext {
	set('springAiVersion', "2.0.0")
}


dependencies {
	// Spring Boot 기본
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.3'

	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'io.micrometer:micrometer-registry-prometheus'

	//jwt
	implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'

    // Stream
	implementation 'io.nats:jnats:2.25.3'

	// S3 OR R2
	implementation 'software.amazon.awssdk:s3:2.54.2'

	// 파일 형식에서 텍스트와 메타데이터를 자동으로 감지하고 추출할 수 있는 오픈소스 라이브러리
	implementation 'org.springframework.ai:spring-ai-tika-document-reader'

	implementation 'org.springframework.ai:spring-ai-starter-model-google-genai'
	implementation 'org.springframework.ai:spring-ai-starter-model-google-genai-embedding'
	implementation 'org.springframework.ai:spring-ai-starter-mcp-client'
	implementation 'org.springframework.ai:spring-ai-starter-mcp-server-webmvc'

	runtimeOnly 'org.postgresql:postgresql'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}


dependencyManagement {
	imports {
		mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
	}
}


tasks.named('test') {
	useJUnitPlatform()
}

tasks.named('bootRun') {
	if (file(".env").exists()) {
		file(".env").readLines().each { line ->
			if (!line.trim().isEmpty() && !line.startsWith("#")) {
				def pos = line.indexOf("=")
				if (pos > 0) {
					def key = line.substring(0, pos).trim()
					def val = line.substring(pos + 1).trim()
					if (val.startsWith("\"") && val.endsWith("\"")) {
						val = val.substring(1, val.length() - 1)
					} else if (val.startsWith("'") && val.endsWith("'")) {
						val = val.substring(1, val.length() - 1)
					}
					environment key, val
				}
			}
		}
	}
}